<a href="https://colab.research.google.com/github/isroilsaparboev-png/python.darslar/blob/main/Random_(5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **randint() ga oid masalalar (1–5)**

1 dan 10 gacha bo‘lgan tasodifiy bitta sonni chiqaruvchi dastur yozing.

In [8]:
from numpy import random
import numpy as np


5 ta elementdan iborat, 0 dan 50 gacha tasodifiy sonlardan iborat massiv yarating.

In [2]:
import random
random_array = [random.randint(0, 50) for _ in range(5)]
print(random_array)

[22, 24, 48, 15, 23]


10 ta tasodifiy son (1–100 oralig‘ida) hosil qiling va ularning yig‘indisini toping.

In [5]:
import random
tasodifiy_sonlar = [random.randint(1, 100) for _ in range(10)]
yigindi = sum(tasodifiy_sonlar)

print(f"Tasodifiy sonlar: {tasodifiy_sonlar}")
print(f"Ularning yig'indisi: {yigindi}")

Tasodifiy sonlar: [21, 18, 21, 10, 33, 55, 48, 71, 93, 93]
Ularning yig'indisi: 463


3x3 o‘lchamli matritsa yarating (elementlari 0–9 oralig‘ida bo‘lsin).

In [12]:
arr = random.randint(0,9, size = (3,3))
arr

array([[4, 5, 4],
       [1, 3, 2],
       [6, 3, 0]])

20 ta tasodifiy son ichidan faqat juft sonlarni ajratib chiqaring.

In [13]:
arr = random.randint(0,100, size = (20))
arr

array([97, 36, 27, 93, 88, 87,  6, 11, 42, 67, 82, 48, 90, 23, 86, 25, 39,
       78, 72, 76])

# **rand() ga oid masalalar (6–10)**

0 va 1 oralig‘ida bitta tasodifiy haqiqiy son chiqaring.

In [14]:
number = random.rand()
number

0.699254410265814

5 ta tasodifiy haqiqiy sonlardan iborat massiv yarating.

In [16]:
number = random.rand(5)
number

array([0.34424243, 0.34004565, 0.97750095, 0.46765956, 0.82764562])

4x2 o‘lchamli matritsa yarating (0–1 oralig‘idagi sonlar bilan).

In [17]:
number = random.rand(4,2)
number

array([[0.53017668, 0.77044254],
       [0.16876435, 0.71743868],
       [0.12096461, 0.32360845],
       [0.74624032, 0.24988163]])

10 ta tasodifiy son hosil qilib, ularning o‘rtacha qiymatini toping.

In [18]:
number = random.rand(10)
np.mean

<function mean at 0x7cb4fd724470>

6 ta tasodifiy son ichidan 0.5 dan kattalarini ajratib chiqaring.

In [20]:
number = random.rand(6)
number[number > 0.5]

array([0.5754548 , 0.60409766, 0.67499287])

# **choice() ga oid masalalar (11–15)**

[1, 2, 3, 4, 5] ro‘yxatdan tasodifiy bitta element tanlang.

In [23]:
list = [1 , 2 , 3 , 4 , 5]
random.choice(list)

np.int64(3)

["olma", "banan", "gilos"] ro‘yxatdan 3 ta tasodifiy element tanlang.

In [25]:
list = ["olma","banan","gilos"]
random.choice(list, size = (3))

array(['gilos', 'banan', 'gilos'], dtype='<U5')

[10, 20, 30, 40] ro‘yxatdan 5 ta tasodifiy son tanlang (takrorlanishi mumkin).

In [26]:
list = [10,20,30,40]
random.choice(list, size = 5)

array([20, 40, 30, 20, 40])

Talabalar ro‘yxatidan (["Ali", "Vali", "Sami"]) tasodifiy 1 nafarini tanlang.

In [27]:
list = ["Ali","Vali","Sami"]
random.choice(list)=

np.str_('Vali')

[1, 2, 3] elementlardan 10 ta tasodifiy tanlab, natijani massiv ko‘rinishida chiqaring.

In [28]:
arr = random.choice([1,2,3], size = (10))
arr

array([1, 3, 1, 2, 2, 2, 1, 2, 3, 1])